const govtList = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "(UT) Andaman and Nicobar Islands",
  "(UT) Chandigarh",
  "(UT) Dadra and Nagar Haveli and Daman & Diu",
  "(UT) The Government of NCT of Delhi",
  "(UT) Jammu & Kashmir",
  "(UT) Ladakh",
  "(UT) Lakshadweep",
  "(UT) Puducherry",
];

export default govtList;
